:hardbreaks-option:

= PasteRB.slim

A service for storing pastes/gists with collaboration.
Anyone with the `/edit` link can modify a paste.
With support for Rack and regular old CGI.

== Running

PasteRB can be served as a https://github.com/rack/rack/blob/main/SPEC.rdoc[Rack] or https://en.wikipedia.org/wiki/CGI[CGI] application.

=== Rack

```SH
bundle install
bundle exec rake db:up
bundle exec rackup
```

=== CGI

This application can completely be run using CGI.
The CGI call would be `/bin/bundle exec src/pasterb.slim`.
When using CGI, expect >500ms response times.

==== CGI via Caddy

The repository includes a sample Caddyfile for development.

To use it set a caddy build from <https://caddyserver.com/download> with https://github.com/aksdb/caddy-cgi[cgi support] and save it as `caddy_cgi`.

```SH
bundle install
bundle exec rake db:up
./caddy_cgi run --config Caddyfile --watch
```

=== Running both for development
Use the `Procfile` to run both caddy and rack while watching the database log.

```
bundle install
bundle exec rake db:up
bundle exec foreman start
```

== Cleaning the database
The logic of the application makes it possible to create empty pastes (a paste with no revisions).
There is a rack task to clean these out.

```
bundle exec rack db:clean
```
